import { PokemonType } from '../types';

export interface MoveDetails {
  name: string;
  type: PokemonType;
  power: number | null;
  accuracy: number | null;
  pp: number;
}

// A mapping of move names to their details, covering moves in the database.
const MOVE_DETAILS_DATA: Record<string, MoveDetails> = {
  'absorb': { name: 'Absorb', type: PokemonType.Grass, power: 20, accuracy: 100, pp: 25 },
  'acupressure': { name: 'Acupressure', type: PokemonType.Normal, power: null, accuracy: null, pp: 30 },
  'aerial ace': { name: 'Aerial Ace', type: PokemonType.Flying, power: 60, accuracy: null, pp: 20 },
  'agility': { name: 'Agility', type: PokemonType.Psychic, power: null, accuracy: null, pp: 30 },
  'air cutter': { name: 'Air Cutter', type: PokemonType.Flying, power: 55, accuracy: 95, pp: 25 },
  'air slash': { name: 'Air Slash', type: PokemonType.Flying, power: 75, accuracy: 95, pp: 20 },
  'ancient power': { name: 'Ancient Power', type: PokemonType.Rock, power: 60, accuracy: 100, pp: 5 },
  'aqua jet': { name: 'Aqua Jet', type: PokemonType.Water, power: 40, accuracy: 100, pp: 20 },
  'aqua ring': { name: 'Aqua Ring', type: PokemonType.Water, power: null, accuracy: null, pp: 20 },
  'aqua tail': { name: 'Aqua Tail', type: PokemonType.Water, power: 90, accuracy: 90, pp: 10 },
  'aromatherapy': { name: 'Aromatherapy', type: PokemonType.Grass, power: null, accuracy: null, pp: 5 },
  'assist': { name: 'Assist', type: PokemonType.Normal, power: null, accuracy: null, pp: 20 },
  'assurance': { name: 'Assurance', type: PokemonType.Dark, power: 50, accuracy: 100, pp: 10 },
  'attract': { name: 'Attract', type: PokemonType.Normal, power: null, accuracy: 100, pp: 15 },
  'aura sphere': { name: 'Aura Sphere', type: PokemonType.Fighting, power: 90, accuracy: null, pp: 20 },
  'aurora beam': { name: 'Aurora Beam', type: PokemonType.Ice, power: 65, accuracy: 100, pp: 20 },
  'avalanche': { name: 'Avalanche', type: PokemonType.Ice, power: 60, accuracy: 100, pp: 10 },
  'baton pass': { name: 'Baton Pass', type: PokemonType.Normal, power: null, accuracy: null, pp: 40 },
  'belly drum': { name: 'Belly Drum', type: PokemonType.Normal, power: null, accuracy: null, pp: 10 },
  'bite': { name: 'Bite', type: PokemonType.Dark, power: 60, accuracy: 100, pp: 25 },
  'blast burn': { name: 'Blast Burn', type: PokemonType.Fire, power: 150, accuracy: 90, pp: 5 },
  'blaze kick': { name: 'Blaze Kick', type: PokemonType.Fire, power: 85, accuracy: 90, pp: 10 },
  'blizzard': { name: 'Blizzard', type: PokemonType.Ice, power: 120, accuracy: 70, pp: 5 },
  'body slam': { name: 'Body Slam', type: PokemonType.Normal, power: 85, accuracy: 100, pp: 15 },
  'bone rush': { name: 'Bone Rush', type: PokemonType.Ground, power: 25, accuracy: 90, pp: 10 },
  'bonemerang': { name: 'Bonemerang', type: PokemonType.Ground, power: 50, accuracy: 90, pp: 10 },
  'bounce': { name: 'Bounce', type: PokemonType.Flying, power: 85, accuracy: 85, pp: 5 },
  'brave bird': { name: 'Brave Bird', type: PokemonType.Flying, power: 120, accuracy: 100, pp: 15 },
  'brick break': { name: 'Brick Break', type: PokemonType.Fighting, power: 75, accuracy: 100, pp: 15 },
  'brine': { name: 'Brine', type: PokemonType.Water, power: 65, accuracy: 100, pp: 10 },
  'bubble': { name: 'Bubble', type: PokemonType.Water, power: 20, accuracy: 100, pp: 30 },
  'bug bite': { name: 'Bug Bite', type: PokemonType.Bug, power: 60, accuracy: 100, pp: 20 },
  'bug buzz': { name: 'Bug Buzz', type: PokemonType.Bug, power: 90, accuracy: 100, pp: 10 },
  'bulk up': { name: 'Bulk Up', type: PokemonType.Fighting, power: null, accuracy: null, pp: 20 },
  'bullet punch': { name: 'Bullet Punch', type: PokemonType.Steel, power: 40, accuracy: 100, pp: 30 },
  'calm mind': { name: 'Calm Mind', type: PokemonType.Psychic, power: null, accuracy: null, pp: 20 },
  'charge beam': { name: 'Charge Beam', type: PokemonType.Electric, power: 50, accuracy: 90, pp: 10 },
  'charm': { name: 'Charm', type: PokemonType.Normal, power: null, accuracy: 100, pp: 20 },
  'close combat': { name: 'Close Combat', type: PokemonType.Fighting, power: 120, accuracy: 100, pp: 5 },
  'confusion': { name: 'Confusion', type: PokemonType.Psychic, power: 50, accuracy: 100, pp: 25 },
  'constrict': { name: 'Constrict', type: PokemonType.Normal, power: 10, accuracy: 100, pp: 35 },
  'copycat': { name: 'Copycat', type: PokemonType.Normal, power: null, accuracy: null, pp: 20 },
  'cosmic power': { name: 'Cosmic Power', type: PokemonType.Psychic, power: null, accuracy: null, pp: 20 },
  'counter': { name: 'Counter', type: PokemonType.Fighting, power: null, accuracy: 100, pp: 20 },
  'crabhammer': { name: 'Crabhammer', type: PokemonType.Water, power: 90, accuracy: 90, pp: 10 },
  'cross chop': { name: 'Cross Chop', type: PokemonType.Fighting, power: 100, accuracy: 80, pp: 5 },
  'cross poison': { name: 'Cross Poison', type: PokemonType.Poison, power: 70, accuracy: 100, pp: 20 },
  'crunch': { name: 'Crunch', type: PokemonType.Dark, power: 80, accuracy: 100, pp: 15 },
  'crush grip': { name: 'Crush Grip', type: PokemonType.Normal, power: null, accuracy: 100, pp: 5 },
  'curse': { name: 'Curse', type: PokemonType.Ghost, power: null, accuracy: null, pp: 10 },
  'dark pulse': { name: 'Dark Pulse', type: PokemonType.Dark, power: 80, accuracy: 100, pp: 15 },
  'dark void': { name: 'Dark Void', type: PokemonType.Dark, power: null, accuracy: 80, pp: 10 },
  'defense curl': { name: 'Defense Curl', type: PokemonType.Normal, power: null, accuracy: null, pp: 40 },
  'defend order': { name: 'Defend Order', type: PokemonType.Bug, power: null, accuracy: null, pp: 10 },
  'destiny bond': { name: 'Destiny Bond', type: PokemonType.Ghost, power: null, accuracy: null, pp: 5 },
  'detect': { name: 'Detect', type: PokemonType.Fighting, power: null, accuracy: null, pp: 5 },
  'dig': { name: 'Dig', type: PokemonType.Ground, power: 80, accuracy: 100, pp: 10 },
  'disable': { name: 'Disable', type: PokemonType.Normal, power: null, accuracy: 100, pp: 20 },
  'discharge': { name: 'Discharge', type: PokemonType.Electric, power: 80, accuracy: 100, pp: 15 },
  'dive': { name: 'Dive', type: PokemonType.Water, power: 80, accuracy: 100, pp: 10 },
  'dizzy punch': { name: 'Dizzy Punch', type: PokemonType.Normal, power: 70, accuracy: 100, pp: 10 },
  'doom desire': { name: 'Doom Desire', type: PokemonType.Steel, power: 140, accuracy: 100, pp: 5 },
  'double hit': { name: 'Double Hit', type: PokemonType.Normal, power: 35, accuracy: 90, pp: 10 },
  'double kick': { name: 'Double Kick', type: PokemonType.Fighting, power: 30, accuracy: 100, pp: 30 },
  'double-edge': { name: 'Double-Edge', type: PokemonType.Normal, power: 120, accuracy: 100, pp: 15 },
  'draco meteor': { name: 'Draco Meteor', type: PokemonType.Dragon, power: 140, accuracy: 90, pp: 5 },
  'dragon claw': { name: 'Dragon Claw', type: PokemonType.Dragon, power: 80, accuracy: 100, pp: 15 },
  'dragon dance': { name: 'Dragon Dance', type: PokemonType.Dragon, power: null, accuracy: null, pp: 20 },
  'dragon pulse': { name: 'Dragon Pulse', type: PokemonType.Dragon, power: 90, accuracy: 100, pp: 10 },
  'dragon rush': { name: 'Dragon Rush', type: PokemonType.Dragon, power: 100, accuracy: 75, pp: 10 },
  'drain punch': { name: 'Drain Punch', type: PokemonType.Fighting, power: 75, accuracy: 100, pp: 10 },
  'dream eater': { name: 'Dream Eater', type: PokemonType.Psychic, power: 100, accuracy: 100, pp: 15 },
  'drill peck': { name: 'Drill Peck', type: PokemonType.Flying, power: 80, accuracy: 100, pp: 20 },
  'dynamic punch': { name: 'Dynamic Punch', type: PokemonType.Fighting, power: 100, accuracy: 50, pp: 5 },
  'earth power': { name: 'Earth Power', type: PokemonType.Ground, power: 90, accuracy: 100, pp: 10 },
  'earthquake': { name: 'Earthquake', type: PokemonType.Ground, power: 100, accuracy: 100, pp: 10 },
  'ember': { name: 'Ember', type: PokemonType.Fire, power: 40, accuracy: 100, pp: 25 },
  'encore': { name: 'Encore', type: PokemonType.Normal, power: null, accuracy: 100, pp: 5 },
  'endeavor': { name: 'Endeavor', type: PokemonType.Normal, power: null, accuracy: 100, pp: 5 },
  'endure': { name: 'Endure', type: PokemonType.Normal, power: null, accuracy: null, pp: 10 },
  'energy ball': { name: 'Energy Ball', type: PokemonType.Grass, power: 80, accuracy: 100, pp: 10 },
  'eruption': { name: 'Eruption', type: PokemonType.Fire, power: 150, accuracy: 100, pp: 5 },
  'explosion': { name: 'Explosion', type: PokemonType.Normal, power: 250, accuracy: 100, pp: 5 },
  'extrasensory': { name: 'Extrasensory', type: PokemonType.Psychic, power: 80, accuracy: 100, pp: 30 },
  'extreme speed': { name: 'Extreme Speed', type: PokemonType.Normal, power: 80, accuracy: 100, pp: 5 },
  'facade': { name: 'Facade', type: PokemonType.Normal, power: 70, accuracy: 100, pp: 20 },
  'fake out': { name: 'Fake Out', type: PokemonType.Normal, power: 40, accuracy: 100, pp: 10 },
  'fake tears': { name: 'Fake Tears', type: PokemonType.Dark, power: null, accuracy: 100, pp: 20 },
  'feather dance': { name: 'Feather Dance', type: PokemonType.Flying, power: null, accuracy: 100, pp: 15 },
  'feint': { name: 'Feint', type: PokemonType.Normal, power: 50, accuracy: 100, pp: 10 },
  'feint attack': { name: 'Feint Attack', type: PokemonType.Dark, power: 60, accuracy: null, pp: 20 },
  'fire blast': { name: 'Fire Blast', type: PokemonType.Fire, power: 120, accuracy: 85, pp: 5 },
  'fire fang': { name: 'Fire Fang', type: PokemonType.Fire, power: 65, accuracy: 95, pp: 15 },
  'fire punch': { name: 'Fire Punch', type: PokemonType.Fire, power: 75, accuracy: 100, pp: 15 },
  'fire spin': { name: 'Fire Spin', type: PokemonType.Fire, power: 35, accuracy: 85, pp: 15 },
  'fissure': { name: 'Fissure', type: PokemonType.Ground, power: null, accuracy: 30, pp: 5 },
  'flail': { name: 'Flail', type: PokemonType.Normal, power: null, accuracy: 100, pp: 15 },
  'flame wheel': { name: 'Flame Wheel', type: PokemonType.Fire, power: 60, accuracy: 100, pp: 25 },
  'flamethrower': { name: 'Flamethrower', type: PokemonType.Fire, power: 95, accuracy: 100, pp: 15 },
  'flare blitz': { name: 'Flare Blitz', type: PokemonType.Fire, power: 120, accuracy: 100, pp: 15 },
  'flash': { name: 'Flash', type: PokemonType.Normal, power: null, accuracy: 100, pp: 20 },
  'flash cannon': { name: 'Flash Cannon', type: PokemonType.Steel, power: 80, accuracy: 100, pp: 10 },
  'flatter': { name: 'Flatter', type: PokemonType.Dark, power: null, accuracy: 100, pp: 15 },
  'fling': { name: 'Fling', type: PokemonType.Dark, power: null, accuracy: 100, pp: 10 },
  'fly': { name: 'Fly', type: PokemonType.Flying, power: 90, accuracy: 95, pp: 15 },
  'focus blast': { name: 'Focus Blast', type: PokemonType.Fighting, power: 120, accuracy: 70, pp: 5 },
  'focus energy': { name: 'Focus Energy', type: PokemonType.Normal, power: null, accuracy: null, pp: 30 },
  'focus punch': { name: 'Focus Punch', type: PokemonType.Fighting, power: 150, accuracy: 100, pp: 20 },
  'follow me': { name: 'Follow Me', type: PokemonType.Normal, power: null, accuracy: null, pp: 20 },
  'frenzy plant': { name: 'Frenzy Plant', type: PokemonType.Grass, power: 150, accuracy: 90, pp: 5 },
  'frustration': { name: 'Frustration', type: PokemonType.Normal, power: null, accuracy: 100, pp: 20 },
  'fury attack': { name: 'Fury Attack', type: PokemonType.Normal, power: 15, accuracy: 85, pp: 20 },
  'future sight': { name: 'Future Sight', type: PokemonType.Psychic, power: 100, accuracy: 100, pp: 10 },
  'gastro acid': { name: 'Gastro Acid', type: PokemonType.Poison, power: null, accuracy: 100, pp: 10 },
  'giga drain': { name: 'Giga Drain', type: PokemonType.Grass, power: 75, accuracy: 100, pp: 10 },
  'giga impact': { name: 'Giga Impact', type: PokemonType.Normal, power: 150, accuracy: 90, pp: 5 },
  'glare': { name: 'Glare', type: PokemonType.Normal, power: null, accuracy: 90, pp: 30 },
  'grass knot': { name: 'Grass Knot', type: PokemonType.Grass, power: null, accuracy: 100, pp: 20 },
  'grass whistle': { name: 'Grass Whistle', type: PokemonType.Grass, power: null, accuracy: 55, pp: 15 },
  'gravity': { name: 'Gravity', type: PokemonType.Psychic, power: null, accuracy: null, pp: 5 },
  'growl': { name: 'Growl', type: PokemonType.Normal, power: null, accuracy: 100, pp: 40 },
  'growth': { name: 'Growth', type: PokemonType.Normal, power: null, accuracy: null, pp: 40 },
  'grudge': { name: 'Grudge', type: PokemonType.Ghost, power: null, accuracy: null, pp: 5 },
  'gunk shot': { name: 'Gunk Shot', type: PokemonType.Poison, power: 120, accuracy: 70, pp: 5 },
  'gyro ball': { name: 'Gyro Ball', type: PokemonType.Steel, power: null, accuracy: 100, pp: 5 },
  'hail': { name: 'Hail', type: PokemonType.Ice, power: null, accuracy: null, pp: 10 },
  'hammer arm': { name: 'Hammer Arm', type: PokemonType.Fighting, power: 100, accuracy: 90, pp: 10 },
  'haze': { name: 'Haze', type: PokemonType.Ice, power: null, accuracy: null, pp: 30 },
  'head smash': { name: 'Head Smash', type: PokemonType.Rock, power: 150, accuracy: 80, pp: 5 },
  'headbutt': { name: 'Headbutt', type: PokemonType.Normal, power: 70, accuracy: 100, pp: 15 },
  'heal bell': { name: 'Heal Bell', type: PokemonType.Normal, power: null, accuracy: null, pp: 5 },
  'heal block': { name: 'Heal Block', type: PokemonType.Psychic, power: null, accuracy: 100, pp: 15 },
  'healing wish': { name: 'Healing Wish', type: PokemonType.Psychic, power: null, accuracy: null, pp: 10 },
  'heart swap': { name: 'Heart Swap', type: PokemonType.Psychic, power: null, accuracy: null, pp: 10 },
  'heat wave': { name: 'Heat Wave', type: PokemonType.Fire, power: 100, accuracy: 90, pp: 10 },
  'helping hand': { name: 'Helping Hand', type: PokemonType.Normal, power: null, accuracy: null, pp: 20 },
  'high jump kick': { name: 'High Jump Kick', type: PokemonType.Fighting, power: 100, accuracy: 90, pp: 20 },
  'hidden power': { name: 'Hidden Power', type: PokemonType.Normal, power: null, accuracy: 100, pp: 15 },
  'hydro cannon': { name: 'Hydro Cannon', type: PokemonType.Water, power: 150, accuracy: 90, pp: 5 },
  'hydro pump': { name: 'Hydro Pump', type: PokemonType.Water, power: 120, accuracy: 80, pp: 5 },
  'hyper beam': { name: 'Hyper Beam', type: PokemonType.Normal, power: 150, accuracy: 90, pp: 5 },
  'hyper voice': { name: 'Hyper Voice', type: PokemonType.Normal, power: 90, accuracy: 100, pp: 10 },
  'hypnosis': { name: 'Hypnosis', type: PokemonType.Psychic, power: null, accuracy: 60, pp: 20 },
  'ice beam': { name: 'Ice Beam', type: PokemonType.Ice, power: 95, accuracy: 100, pp: 10 },
  'ice fang': { name: 'Ice Fang', type: PokemonType.Ice, power: 65, accuracy: 95, pp: 15 },
  'ice punch': { name: 'Ice Punch', type: PokemonType.Ice, power: 75, accuracy: 100, pp: 15 },
  'ice shard': { name: 'Ice Shard', type: PokemonType.Ice, power: 40, accuracy: 100, pp: 30 },
  'icicle spear': { name: 'Icicle Spear', type: PokemonType.Ice, power: 25, accuracy: 100, pp: 30 },
  'icy wind': { name: 'Icy Wind', type: PokemonType.Ice, power: 55, accuracy: 95, pp: 15 },
  'imprison': { name: 'Imprison', type: PokemonType.Psychic, power: null, accuracy: null, pp: 10 },
  'ingrain': { name: 'Ingrain', type: PokemonType.Grass, power: null, accuracy: null, pp: 20 },
  'iron defense': { name: 'Iron Defense', type: PokemonType.Steel, power: null, accuracy: null, pp: 15 },
  'iron head': { name: 'Iron Head', type: PokemonType.Steel, power: 80, accuracy: 100, pp: 15 },
  'iron tail': { name: 'Iron Tail', type: PokemonType.Steel, power: 100, accuracy: 75, pp: 15 },
  'judgment': { name: 'Judgment', type: PokemonType.Normal, power: 100, accuracy: 100, pp: 10 },
  'kinesis': { name: 'Kinesis', type: PokemonType.Psychic, power: null, accuracy: 80, pp: 15 },
  'knock off': { name: 'Knock Off', type: PokemonType.Dark, power: 20, accuracy: 100, pp: 20 },
  'last resort': { name: 'Last Resort', type: PokemonType.Normal, power: 140, accuracy: 100, pp: 5 },
  'lava plume': { name: 'Lava Plume', type: PokemonType.Fire, power: 80, accuracy: 100, pp: 15 },
  'leaf blade': { name: 'Leaf Blade', type: PokemonType.Grass, power: 90, accuracy: 100, pp: 15 },
  'leaf storm': { name: 'Leaf Storm', type: PokemonType.Grass, power: 140, accuracy: 90, pp: 5 },
  'leech seed': { name: 'Leech Seed', type: PokemonType.Grass, power: null, accuracy: 90, pp: 10 },
  'leer': { name: 'Leer', type: PokemonType.Normal, power: null, accuracy: 100, pp: 30 },
  'lick': { name: 'Lick', type: PokemonType.Ghost, power: 20, accuracy: 100, pp: 30 },
  'light screen': { name: 'Light Screen', type: PokemonType.Psychic, power: null, accuracy: null, pp: 30 },
  'lock-on': { name: 'Lock-On', type: PokemonType.Normal, power: null, accuracy: null, pp: 5 },
  'low kick': { name: 'Low Kick', type: PokemonType.Fighting, power: null, accuracy: 100, pp: 20 },
  'lovely kiss': { name: 'Lovely Kiss', type: PokemonType.Normal, power: null, accuracy: 75, pp: 10 },
  'lunar dance': { name: 'Lunar Dance', type: PokemonType.Psychic, power: null, accuracy: null, pp: 10 },
  'luster purge': { name: 'Luster Purge', type: PokemonType.Psychic, power: 70, accuracy: 100, pp: 5 },
  'mach punch': { name: 'Mach Punch', type: PokemonType.Fighting, power: 40, accuracy: 100, pp: 30 },
  'magic coat': { name: 'Magic Coat', type: PokemonType.Psychic, power: null, accuracy: null, pp: 15 },
  'magma storm': { name: 'Magma Storm', type: PokemonType.Fire, power: 120, accuracy: 75, pp: 5 },
  'magnet rise': { name: 'Magnet Rise', type: PokemonType.Electric, power: null, accuracy: null, pp: 10 },
  'me first': { name: 'Me First', type: PokemonType.Normal, power: null, accuracy: null, pp: 20 },
  'mean look': { name: 'Mean Look', type: PokemonType.Normal, power: null, accuracy: null, pp: 5 },
  'mega drain': { name: 'Mega Drain', type: PokemonType.Grass, power: 40, accuracy: 100, pp: 15 },
  'megahorn': { name: 'Megahorn', type: PokemonType.Bug, power: 120, accuracy: 85, pp: 10 },
  'memento': { name: 'Memento', type: PokemonType.Dark, power: null, accuracy: 100, pp: 10 },
  'metal burst': { name: 'Metal Burst', type: PokemonType.Steel, power: null, accuracy: 100, pp: 10 },
  'metal claw': { name: 'Metal Claw', type: PokemonType.Steel, power: 50, accuracy: 95, pp: 35 },
  'meteor mash': { name: 'Meteor Mash', type: PokemonType.Steel, power: 100, accuracy: 85, pp: 10 },
  'metronome': { name: 'Metronome', type: PokemonType.Normal, power: null, accuracy: null, pp: 10 },
  'milk drink': { name: 'Milk Drink', type: PokemonType.Normal, power: null, accuracy: null, pp: 10 },
  'mimic': { name: 'Mimic', type: PokemonType.Normal, power: null, accuracy: null, pp: 10 },
  'mirror coat': { name: 'Mirror Coat', type: PokemonType.Psychic, power: null, accuracy: 100, pp: 20 },
  'mirror move': { name: 'Mirror Move', type: PokemonType.Flying, power: null, accuracy: null, pp: 20 },
  'mirror shot': { name: 'Mirror Shot', type: PokemonType.Steel, power: 65, accuracy: 85, pp: 10 },
  'mist': { name: 'Mist', type: PokemonType.Ice, power: null, accuracy: null, pp: 30 },
  'mist ball': { name: 'Mist Ball', type: PokemonType.Psychic, power: 70, accuracy: 100, pp: 5 },
  'morning sun': { name: 'Morning Sun', type: PokemonType.Normal, power: null, accuracy: null, pp: 5 },
  'mud-slap': { name: 'Mud-Slap', type: PokemonType.Ground, power: 20, accuracy: 100, pp: 10 },
  'muddy water': { name: 'Muddy Water', type: PokemonType.Water, power: 95, accuracy: 85, pp: 10 },
  'nasty plot': { name: 'Nasty Plot', type: PokemonType.Dark, power: null, accuracy: null, pp: 20 },
  'natural gift': { name: 'Natural Gift', type: PokemonType.Normal, power: null, accuracy: 100, pp: 15 },
  'needle arm': { name: 'Needle Arm', type: PokemonType.Grass, power: 60, accuracy: 100, pp: 15 },
  'night shade': { name: 'Night Shade', type: PokemonType.Ghost, power: null, accuracy: 100, pp: 15 },
  'night slash': { name: 'Night Slash', type: PokemonType.Dark, power: 70, accuracy: 100, pp: 15 },
  'nightmare': { name: 'Nightmare', type: PokemonType.Ghost, power: null, accuracy: 100, pp: 15 },
  'octazooka': { name: 'Octazooka', type: PokemonType.Water, power: 65, accuracy: 85, pp: 10 },
  'ominous wind': { name: 'Ominous Wind', type: PokemonType.Ghost, power: 60, accuracy: 100, pp: 5 },
  'outrage': { name: 'Outrage', type: PokemonType.Dragon, power: 120, accuracy: 100, pp: 15 },
  'overheat': { name: 'Overheat', type: PokemonType.Fire, power: 140, accuracy: 90, pp: 5 },
  'pain split': { name: 'Pain Split', type: PokemonType.Normal, power: null, accuracy: null, pp: 20 },
  'payback': { name: 'Payback', type: PokemonType.Dark, power: 50, accuracy: 100, pp: 10 },
  'peck': { name: 'Peck', type: PokemonType.Flying, power: 35, accuracy: 100, pp: 35 },
  'perish song': { name: 'Perish Song', type: PokemonType.Normal, power: null, accuracy: null, pp: 5 },
  'pluck': { name: 'Pluck', type: PokemonType.Flying, power: 60, accuracy: 100, pp: 20 },
  'poison fang': { name: 'Poison Fang', type: PokemonType.Poison, power: 50, accuracy: 100, pp: 15 },
  'poison jab': { name: 'Poison Jab', type: PokemonType.Poison, power: 80, accuracy: 100, pp: 20 },
  'poison sting': { name: 'Poison Sting', type: PokemonType.Poison, power: 15, accuracy: 100, pp: 35 },
  'poisonpowder': { name: 'PoisonPowder', type: PokemonType.Poison, power: null, accuracy: 75, pp: 35 },
  'pound': { name: 'Pound', type: PokemonType.Normal, power: 40, accuracy: 100, pp: 35 },
  'power gem': { name: 'Power Gem', type: PokemonType.Rock, power: 70, accuracy: 100, pp: 20 },
  'power trick': { name: 'Power Trick', type: PokemonType.Psychic, power: null, accuracy: null, pp: 10 },
  'power whip': { name: 'Power Whip', type: PokemonType.Grass, power: 120, accuracy: 85, pp: 10 },
  'protect': { name: 'Protect', type: PokemonType.Normal, power: null, accuracy: null, pp: 10 },
  'psybeam': { name: 'Psybeam', type: PokemonType.Psychic, power: 65, accuracy: 100, pp: 20 },
  'psych up': { name: 'Psych Up', type: PokemonType.Normal, power: null, accuracy: null, pp: 10 },
  'psychic': { name: 'Psychic', type: PokemonType.Psychic, power: 90, accuracy: 100, pp: 10 },
  'psycho boost': { name: 'Psycho Boost', type: PokemonType.Psychic, power: 140, accuracy: 90, pp: 5 },
  'psycho cut': { name: 'Psycho Cut', type: PokemonType.Psychic, power: 70, accuracy: 100, pp: 20 },
  'psycho shift': { name: 'Psycho Shift', type: PokemonType.Psychic, power: null, accuracy: 90, pp: 10 },
  'punishment': { name: 'Punishment', type: PokemonType.Dark, power: null, accuracy: 100, pp: 5 },
  'pursuit': { name: 'Pursuit', type: PokemonType.Dark, power: 40, accuracy: 100, pp: 20 },
  'quick attack': { name: 'Quick Attack', type: PokemonType.Normal, power: 40, accuracy: 100, pp: 30 },
  'rain dance': { name: 'Rain Dance', type: PokemonType.Water, power: null, accuracy: null, pp: 5 },
  'rapid spin': { name: 'Rapid Spin', type: PokemonType.Normal, power: 20, accuracy: 100, pp: 40 },
  'razor wind': { name: 'Razor Wind', type: PokemonType.Normal, power: 80, accuracy: 100, pp: 10 },
  'recover': { name: 'Recover', type: PokemonType.Normal, power: null, accuracy: null, pp: 10 },
  'reflect': { name: 'Reflect', type: PokemonType.Psychic, power: null, accuracy: null, pp: 20 },
  'rest': { name: 'Rest', type: PokemonType.Psychic, power: null, accuracy: null, pp: 10 },
  'return': { name: 'Return', type: PokemonType.Normal, power: null, accuracy: 100, pp: 20 },
  'reversal': { name: 'Reversal', type: PokemonType.Fighting, power: null, accuracy: 100, pp: 15 },
  'roar': { name: 'Roar', type: PokemonType.Normal, power: null, accuracy: 100, pp: 20 },
  'roar of time': { name: 'Roar of Time', type: PokemonType.Dragon, power: 150, accuracy: 90, pp: 5 },
  'rock blast': { name: 'Rock Blast', type: PokemonType.Rock, power: 25, accuracy: 90, pp: 10 },
  'rock polish': { name: 'Rock Polish', type: PokemonType.Rock, power: null, accuracy: null, pp: 20 },
  'rock slide': { name: 'Rock Slide', type: PokemonType.Rock, power: 75, accuracy: 90, pp: 10 },
  'rock smash': { name: 'Rock Smash', type: PokemonType.Fighting, power: 40, accuracy: 100, pp: 15 },
  'rock tomb': { name: 'Rock Tomb', type: PokemonType.Rock, power: 50, accuracy: 80, pp: 10 },
  'rolling kick': { name: 'Rolling Kick', type: PokemonType.Fighting, power: 60, accuracy: 85, pp: 15 },
  'rollout': { name: 'Rollout', type: PokemonType.Rock, power: 30, accuracy: 90, pp: 20 },
  'roost': { name: 'Roost', type: PokemonType.Flying, power: null, accuracy: null, pp: 10 },
  'sacred fire': { name: 'Sacred Fire', type: PokemonType.Fire, power: 100, accuracy: 95, pp: 5 },
  'safeguard': { name: 'Safeguard', type: PokemonType.Normal, power: null, accuracy: null, pp: 25 },
  'sandstorm': { name: 'Sandstorm', type: PokemonType.Rock, power: null, accuracy: null, pp: 10 },
  'scratch': { name: 'Scratch', type: PokemonType.Normal, power: 40, accuracy: 100, pp: 35 },
  'secret power': { name: 'Secret Power', type: PokemonType.Normal, power: 70, accuracy: 100, pp: 20 },
  'seed bomb': { name: 'Seed Bomb', type: PokemonType.Grass, power: 80, accuracy: 100, pp: 15 },
  'seed flare': { name: 'Seed Flare', type: PokemonType.Grass, power: 120, accuracy: 85, pp: 5 },
  'seismic toss': { name: 'Seismic Toss', type: PokemonType.Fighting, power: null, accuracy: 100, pp: 20 },
  'self-destruct': { name: 'Self-Destruct', type: PokemonType.Normal, power: 200, accuracy: 100, pp: 5 },
  'shadow ball': { name: 'Shadow Ball', type: PokemonType.Ghost, power: 80, accuracy: 100, pp: 15 },
  'shadow claw': { name: 'Shadow Claw', type: PokemonType.Ghost, power: 70, accuracy: 100, pp: 15 },
  'shadow force': { name: 'Shadow Force', type: PokemonType.Ghost, power: 120, accuracy: 100, pp: 5 },
  'shadow sneak': { name: 'Shadow Sneak', type: PokemonType.Ghost, power: 40, accuracy: 100, pp: 30 },
  'sheer cold': { name: 'Sheer Cold', type: PokemonType.Ice, power: null, accuracy: 30, pp: 5 },
  'shock wave': { name: 'Shock Wave', type: PokemonType.Electric, power: 60, accuracy: null, pp: 20 },
  'signal beam': { name: 'Signal Beam', type: PokemonType.Bug, power: 75, accuracy: 100, pp: 15 },
  'sing': { name: 'Sing', type: PokemonType.Normal, power: null, accuracy: 55, pp: 15 },
  'skill swap': { name: 'Skill Swap', type: PokemonType.Psychic, power: null, accuracy: null, pp: 10 },
  'skull bash': { name: 'Skull Bash', type: PokemonType.Normal, power: 130, accuracy: 100, pp: 10 },
  'sky attack': { name: 'Sky Attack', type: PokemonType.Flying, power: 140, accuracy: 90, pp: 5 },
  'sky uppercut': { name: 'Sky Uppercut', type: PokemonType.Fighting, power: 85, accuracy: 90, pp: 15 },
  'slack off': { name: 'Slack Off', type: PokemonType.Normal, power: null, accuracy: null, pp: 10 },
  'slash': { name: 'Slash', type: PokemonType.Normal, power: 70, accuracy: 100, pp: 20 },
  'sleep powder': { name: 'Sleep Powder', type: PokemonType.Grass, power: null, accuracy: 75, pp: 15 },
  'sleep talk': { name: 'Sleep Talk', type: PokemonType.Normal, power: null, accuracy: null, pp: 10 },
  'sludge bomb': { name: 'Sludge Bomb', type: PokemonType.Poison, power: 90, accuracy: 100, pp: 10 },
  'snatch': { name: 'Snatch', type: PokemonType.Dark, power: null, accuracy: null, pp: 10 },
  'solar beam': { name: 'Solar Beam', type: PokemonType.Grass, power: 120, accuracy: 100, pp: 10 },
  'spacial rend': { name: 'Spacial Rend', type: PokemonType.Dragon, power: 100, accuracy: 95, pp: 5 },
  'spikes': { name: 'Spikes', type: PokemonType.Ground, power: null, accuracy: null, pp: 20 },
  'spite': { name: 'Spite', type: PokemonType.Ghost, power: null, accuracy: 100, pp: 10 },
  'splash': { name: 'Splash', type: PokemonType.Normal, power: null, accuracy: null, pp: 40 },
  'spore': { name: 'Spore', type: PokemonType.Grass, power: null, accuracy: 100, pp: 15 },
  'stealth rock': { name: 'Stealth Rock', type: PokemonType.Rock, power: null, accuracy: null, pp: 20 },
  'steel wing': { name: 'Steel Wing', type: PokemonType.Steel, power: 70, accuracy: 90, pp: 25 },
  'stockpile': { name: 'Stockpile', type: PokemonType.Normal, power: null, accuracy: null, pp: 20 },
  'stomp': { name: 'Stomp', type: PokemonType.Normal, power: 65, accuracy: 100, pp: 20 },
  'stone edge': { name: 'Stone Edge', type: PokemonType.Rock, power: 100, accuracy: 80, pp: 5 },
  'stun spore': { name: 'Stun Spore', type: PokemonType.Grass, power: null, accuracy: 75, pp: 30 },
  'substitute': { name: 'Substitute', type: PokemonType.Normal, power: null, accuracy: null, pp: 10 },
  'sucker punch': { name: 'Sucker Punch', type: PokemonType.Dark, power: 80, accuracy: 100, pp: 5 },
  'sunny day': { name: 'Sunny Day', type: PokemonType.Fire, power: null, accuracy: null, pp: 5 },
  'super fang': { name: 'Super Fang', type: PokemonType.Normal, power: null, accuracy: 90, pp: 10 },
  'superpower': { name: 'Superpower', type: PokemonType.Fighting, power: 120, accuracy: 100, pp: 5 },
  'supersonic': { name: 'Supersonic', type: PokemonType.Normal, power: null, accuracy: 55, pp: 20 },
  'surf': { name: 'Surf', type: PokemonType.Water, power: 95, accuracy: 100, pp: 15 },
  'swagger': { name: 'Swagger', type: PokemonType.Normal, power: null, accuracy: 90, pp: 15 },
  'swift': { name: 'Swift', type: PokemonType.Normal, power: 60, accuracy: null, pp: 20 },
  'switcheroo': { name: 'Switcheroo', type: PokemonType.Dark, power: null, accuracy: 100, pp: 10 },
  'swords dance': { name: 'Swords Dance', type: PokemonType.Normal, power: null, accuracy: null, pp: 30 },
  'synthesis': { name: 'Synthesis', type: PokemonType.Grass, power: null, accuracy: null, pp: 5 },
  'tackle': { name: 'Tackle', type: PokemonType.Normal, power: 35, accuracy: 95, pp: 35 },
  'tail glow': { name: 'Tail Glow', type: PokemonType.Bug, power: null, accuracy: null, pp: 20 },
  'tail whip': { name: 'Tail Whip', type: PokemonType.Normal, power: null, accuracy: 100, pp: 30 },
  'tailwind': { name: 'Tailwind', type: PokemonType.Flying, power: null, accuracy: null, pp: 30 },
  'taunt': { name: 'Taunt', type: PokemonType.Dark, power: null, accuracy: 100, pp: 20 },
  'teeter dance': { name: 'Teeter Dance', type: PokemonType.Normal, power: null, accuracy: 100, pp: 20 },
  'thief': { name: 'Thief', type: PokemonType.Dark, power: 40, accuracy: 100, pp: 10 },
  'thunder': { name: 'Thunder', type: PokemonType.Electric, power: 120, accuracy: 70, pp: 10 },
  'thunder fang': { name: 'Thunder Fang', type: PokemonType.Electric, power: 65, accuracy: 95, pp: 15 },
  'thunder punch': { name: 'Thunder Punch', type: PokemonType.Electric, power: 75, accuracy: 100, pp: 15 },
  'thunder wave': { name: 'Thunder Wave', type: PokemonType.Electric, power: null, accuracy: 100, pp: 20 },
  'thunderbolt': { name: 'Thunderbolt', type: PokemonType.Electric, power: 95, accuracy: 100, pp: 15 },
  'torment': { name: 'Torment', type: PokemonType.Dark, power: null, accuracy: 100, pp: 15 },
  'toxic': { name: 'Toxic', type: PokemonType.Poison, power: null, accuracy: 90, pp: 10 },
  'toxic spikes': { name: 'Toxic Spikes', type: PokemonType.Poison, power: null, accuracy: null, pp: 20 },
  'transform': { name: 'Transform', type: PokemonType.Normal, power: null, accuracy: null, pp: 10 },
  'tri attack': { name: 'Tri Attack', type: PokemonType.Normal, power: 80, accuracy: 100, pp: 10 },
  'trick': { name: 'Trick', type: PokemonType.Psychic, power: null, accuracy: 100, pp: 10 },
  'trick room': { name: 'Trick Room', type: PokemonType.Psychic, power: null, accuracy: null, pp: 5 },
  'twineedle': { name: 'Twineedle', type: PokemonType.Bug, power: 25, accuracy: 100, pp: 20 },
  'twister': { name: 'Twister', type: PokemonType.Dragon, power: 40, accuracy: 100, pp: 20 },
  'u-turn': { name: 'U-turn', type: PokemonType.Bug, power: 70, accuracy: 100, pp: 20 },
  'vacuum wave': { name: 'Vacuum Wave', type: PokemonType.Fighting, power: 40, accuracy: 100, pp: 30 },
  'vine whip': { name: 'Vine Whip', type: PokemonType.Grass, power: 35, accuracy: 100, pp: 10 },
  'volt tackle': { name: 'Volt Tackle', type: PokemonType.Electric, power: 120, accuracy: 100, pp: 15 },
  'water gun': { name: 'Water Gun', type: PokemonType.Water, power: 40, accuracy: 100, pp: 25 },
  'water pulse': { name: 'Water Pulse', type: PokemonType.Water, power: 60, accuracy: 100, pp: 20 },
  'water spout': { name: 'Water Spout', type: PokemonType.Water, power: 150, accuracy: 100, pp: 5 },
  'waterfall': { name: 'Waterfall', type: PokemonType.Water, power: 80, accuracy: 100, pp: 15 },
  'weather ball': { name: 'Weather Ball', type: PokemonType.Normal, power: 50, accuracy: 100, pp: 10 },
  'whirlpool': { name: 'Whirlpool', type: PokemonType.Water, power: 35, accuracy: 85, pp: 15 },
  'whirlwind': { name: 'Whirlwind', type: PokemonType.Normal, power: null, accuracy: 100, pp: 20 },
  'will-o-wisp': { name: 'Will-O-Wisp', type: PokemonType.Fire, power: null, accuracy: 75, pp: 15 },
  'wing attack': { name: 'Wing Attack', type: PokemonType.Flying, power: 60, accuracy: 100, pp: 35 },
  'wish': { name: 'Wish', type: PokemonType.Normal, power: null, accuracy: null, pp: 10 },
  'withdraw': { name: 'Withdraw', type: PokemonType.Water, power: null, accuracy: null, pp: 40 },
  'wood hammer': { name: 'Wood Hammer', type: PokemonType.Grass, power: 120, accuracy: 100, pp: 15 },
  'worry seed': { name: 'Worry Seed', type: PokemonType.Grass, power: null, accuracy: 100, pp: 10 },
  'wring out': { name: 'Wring Out', type: PokemonType.Normal, power: null, accuracy: 100, pp: 5 },
  'x-scissor': { name: 'X-Scissor', type: PokemonType.Bug, power: 80, accuracy: 100, pp: 15 },
  'yawn': { name: 'Yawn', type: PokemonType.Normal, power: null, accuracy: null, pp: 10 },
  'zap cannon': { name: 'Zap Cannon', type: PokemonType.Electric, power: 120, accuracy: 50, pp: 5 },
  'zen headbutt': { name: 'Zen Headbutt', type: PokemonType.Psychic, power: 80, accuracy: 90, pp: 15 },
};

/**
 * Gets the detailed information for a move.
 * @param moveName The name of the move.
 * @returns The MoveDetails object, or undefined if not found.
 */
export const getMoveDetails = (moveName: string): MoveDetails | undefined => {
  if (!moveName) return undefined;
  return MOVE_DETAILS_DATA[moveName.toLowerCase()];
};


/**
 * Gets the type of a move.
 * @param moveName The name of the move.
 * @returns The PokemonType of the move, or undefined if not found.
 */
export const getMoveType = (moveName: string): PokemonType | undefined => {
  return getMoveDetails(moveName)?.type;
};