// Data sourced from: https://wiki.dolphin-emu.org/index.php?title=Pok%C3%A9mon_Battle_Revolution#Rental_Passes
const POKEMON_TO_RENTAL_PASS_MAP: Map<string, string[]> = new Map([
    // Colosseum Passes
    ['Pikachu', ['Gateway Colosseum Pass']],
    ['Electabuzz', ['Gateway Colosseum Pass']],
    ['Raichu', ['Gateway Colosseum Pass']],
    ['Jolteon', ['Gateway Colosseum Pass']],
    ['Magnezone', ['Gateway Colosseum Pass']],
    ['Manectric', ['Gateway Colosseum Pass']],
    ['Charizard', ['Main Street Colosseum Pass']],
    ['Arcanine', ['Main Street Colosseum Pass']],
    ['Ninetales', ['Main Street Colosseum Pass']],
    ['Flareon', ['Main Street Colosseum Pass']],
    ['Houndoom', ['Main Street Colosseum Pass']],
    ['Magmortar', ['Main Street Colosseum Pass', 'Pokétopia Pass']],
    ['Blastoise', ['Waterfall Colosseum Pass']],
    ['Vaporeon', ['Waterfall Colosseum Pass']],
    ['Gyarados', ['Waterfall Colosseum Pass']],
    ['Lapras', ['Waterfall Colosseum Pass']],
    ['Milotic', ['Waterfall Colosseum Pass']],
    ['Starmie', ['Waterfall Colosseum Pass']],
    ['Gengar', ['Neon Colosseum Pass']],
    ['Alakazam', ['Neon Colosseum Pass']],
    ['Espeon', ['Neon Colosseum Pass']],
    ['Gardevoir', ['Neon Colosseum Pass']],
    ['Mismagius', ['Neon Colosseum Pass']],
    ['Gallade', ['Neon Colosseum Pass', 'Pokétopia Pass']],
    ['Tyranitar', ['Crystal Colosseum Pass']],
    ['Rhyperior', ['Crystal Colosseum Pass']],
    ['Aggron', ['Crystal Colosseum Pass']],
    ['Golem', ['Crystal Colosseum Pass']],
    ['Steelix', ['Crystal Colosseum Pass']],
    ['Probopass', ['Crystal Colosseum Pass']],
    ['Machamp', ['Courtyard Colosseum Pass']],
    ['Breloom', ['Courtyard Colosseum Pass']],
    ['Heracross', ['Courtyard Colosseum Pass']],
    ['Lucario', ['Courtyard Colosseum Pass', 'Pokétopia Pass']],
    ['Toxicroak', ['Courtyard Colosseum Pass']],
    ['Hariyama', ['Courtyard Colosseum Pass']],
    ['Venusaur', ['Stargazer Colosseum Pass']],
    ['Roserade', ['Stargazer Colosseum Pass']],
    ['Leafeon', ['Stargazer Colosseum Pass']],
    ['Tangrowth', ['Stargazer Colosseum Pass', 'Pokétopia Pass']],
    ['Sceptile', ['Stargazer Colosseum Pass']],
    ['Abomasnow', ['Stargazer Colosseum Pass']],
    ['Dragonite', ['Sunset Colosseum Pass']],
    ['Salamence', ['Sunset Colosseum Pass']],
    ['Garchomp', ['Sunset Colosseum Pass']],
    ['Latios', ['Sunset Colosseum Pass', 'Global Rental Pass', 'Masters Battle Pass']],
    ['Flygon', ['Sunset Colosseum Pass']],
    ['Kingdra', ['Sunset Colosseum Pass']],
    ['Crobat', ['Lagoon Colosseum Pass']],
    ['Weavile', ['Lagoon Colosseum Pass']],
    ['Staraptor', ['Lagoon Colosseum Pass']],
    ['Aerodactyl', ['Lagoon Colosseum Pass']],
    ['Ambipom', ['Lagoon Colosseum Pass']],
    ['Yanmega', ['Lagoon Colosseum Pass']],
    ['Snorlax', ['Sunny Park Colosseum Pass']],
    ['Blissey', ['Sunny Park Colosseum Pass']],
    ['Umbreon', ['Sunny Park Colosseum Pass']],
    ['Dusknoir', ['Sunny Park Colosseum Pass']],
    ['Togekiss', ['Sunny Park Colosseum Pass']],
    ['Metagross', ['Sunny Park Colosseum Pass', 'Masters Battle Pass']],

    // Battle Passes
    ['Raikou', ['Global Rental Pass']],
    ['Entei', ['Global Rental Pass']],
    ['Suicune', ['Global Rental Pass']],
    ['Latias', ['Global Rental Pass', 'Masters Battle Pass']],
    ['Jirachi', ['Global Rental Pass']],
    ['Elekid', ['Little Cup Pass']],
    ['Magby', ['Little Cup Pass']],
    ['Smoochum', ['Little Cup Pass']],
    ['Riolu', ['Little Cup Pass']],
    ['Pichu', ['Little Cup Pass']],
    ['Togepi', ['Little Cup Pass']],
    ['Pachirisu', ['Light Cup Pass']],
    ['Floatzel', ['Light Cup Pass']],
    ['Drifblim', ['Light Cup Pass']],
    ['Cherrim', ['Light Cup Pass']],
    ['Lopunny', ['Light Cup Pass']],
    ['Purugly', ['Light Cup Pass']],
    ['Electivire', ['Pokétopia Pass']],
    ['Gastrodon', ['Pokétopia Pass']],
    ['Cresselia', ['Masters Battle Pass']],
    ['Heatran', ['Masters Battle Pass']],
    ['Regigigas', ['Masters Battle Pass']],
]);

export const getRentalPassesForPokemon = (pokemonName: string): string[] | undefined => {
    return POKEMON_TO_RENTAL_PASS_MAP.get(pokemonName);
};